export const bookData = [
    {
        id: 1,
        libraryName: 'Swaroopa Books',
        bookName: 'Kite Runner',
        bookCategory: 'Fiction',
        bookAuthor: 'Khaled Hosseini',
        bookStatus: 'Availbale',
        bookshelfId: 10236,
    },
    {
        id: 2,
        libraryName: 'Dhrishya Books',
        bookName: 'To Kill a Mockingbird',
        bookCategory: 'Fiction',
        bookAuthor: 'Harper Lee',
        bookStatus: 'Availbale',
        bookshelfId: 10241,
    },
    {
        id: 3,
        libraryName: 'Himlet Books',
        bookName: '1984',
        bookCategory: 'Fiction',
        bookAuthor: 'George Orwell',
        bookStatus: 'Availbale',
        bookshelfId: 10457,
    },
    {
        id: 4,
        libraryName: 'Terminal Books',
        bookName: 'Harry Potter and the Philosopher\'s Stone',
        bookCategory: 'Fiction',
        bookAuthor: 'J.K. Rowling',
        bookStatus: 'Availbale',
        bookshelfId: 10547,
    },
    {
        id: 5,
        libraryName: 'Kites Books',
        bookName: 'The Lord of the Rings',
        bookCategory: 'Fiction',
        bookAuthor: 'J.R.R. Tolkien',
        bookStatus: 'Availbale',
        bookshelfId: 10426,
    },
    {
        id: 6,
        libraryName: 'Dintis Books',
        bookName: 'The Diary Of A Young Girl',
        bookCategory: 'Authobiography',
        bookAuthor: 'Anne Frank',
        bookStatus: 'Availbale',
        bookshelfId: 10257,
    }
]