export const libraryData = [
    {
        id: 1,
        libraryName: 'Swaroopa Books',
        libraryLocation: 'Cherai',
        state: 'Kerala',
        district: 'Ernakulam',
        librarianName: 'Arun VK',
        bookshelfId: 21022,
        contactNumber: '8921980007',
    },
    {
        id: 2,
        libraryName: 'Dhrishya Books',
        libraryLocation: 'Vakkur',
        state: 'Tamil Nadu',
        district: 'Cuddalure',
        librarianName: 'Ramadas',
        bookshelfId: 21010,
        contactNumber: '8921980007',
    },
    {
        id: 3,
        libraryName: 'Himlet Books',
        libraryLocation: 'Eloor',
        state: 'Kerala',
        district: 'Ernakulam',
        librarianName: 'Devana',
        bookshelfId: 21035,
        contactNumber: '8921980007',
    },
    {
        id: 4,
        libraryName: 'Terminal Books',
        libraryLocation: 'Edavana',
        state: 'Kerala',
        district: 'Kottayam',
        librarianName: 'Nayana',
        bookshelfId: 21031,
        contactNumber: '8921980007',
    },
    {
        id: 5,
        libraryName: 'Kites Books',
        libraryLocation: 'Nemam',
        state: 'Kerala',
        district: 'Kottayam',
        librarianName: 'Jaseel',
        bookshelfId: 21075,
        contactNumber: '8921980007',
    },
    {
        id: 6,
        libraryName: 'Dintis Books',
        libraryLocation: 'Vellure',
        state: 'Tamil Nadu',
        district: 'Villupuram',
        librarianName: 'Seenivasan',
        bookshelfId: 21084,
        contactNumber: '8921980007',
    }
]